openapi: 3.0.2
info:
  title: camelo--banckend
  version: 1.0.0
paths:
  /categorias:
    get:
      responses:
        '200':
          $ref: '#/components/responses/CategoriasResponse'
        '400':
          $ref: '#/components/responses/InfoErro'
        '404':
          $ref: '#/components/responses/InfoErro'
        '500':
          $ref: '#/components/responses/InfoErro'
  /produtos:
    get:
      parameters:
        -
          name: idProduto
          description: ''
          schema:
            type: number
          in: query
          required: true
      responses:
        '200':
          $ref: '#/components/responses/ProdutoReponse'
        '204':
          $ref: '#/components/responses/InfoErro'
        '404':
          $ref: '#/components/responses/InfoErro'
        '500':
          $ref: '#/components/responses/InfoErro'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
            examples:
              Payload Criacao Produto:
                value:
                  nome: some text
                  url: some text
                  preco: 96.31
        required: true
      responses:
        '201':
          $ref: '#/components/responses/ProdutoReponse'
        '400':
          $ref: '#/components/responses/InfoErro'
        '404':
          $ref: '#/components/responses/InfoErro'
        '500':
          $ref: '#/components/responses/InfoErro'
  /produtos/promocao:
    get:
      responses:
        '200':
          $ref: '#/components/responses/ProdutosEmPromocao'
        '400':
          $ref: '#/components/responses/InfoErro'
        '404':
          $ref: '#/components/responses/InfoErro'
        '500':
          $ref: '#/components/responses/InfoErro'
  /produtos/categorizado:
    get:
      responses:
        '200':
          $ref: '#/components/responses/ProdutoCategorizado'
        '400':
          $ref: '#/components/responses/InfoErro'
        '404':
          $ref: '#/components/responses/InfoErro'
        '500':
          $ref: '#/components/responses/InfoErro'
  /pagamento:
    get:
      parameters:
        -
          examples:
            Bearer token:
              value: >-
                Bearer
                eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjYXJsb3NAZ21haWwuY29tIiwiZXhwIjoxNjM2NTk0ODM2fQ.VkshuIq_WYWjTFgTFZ_N5JY5n1fDFmg4dXuR1B198u4UCAReBpFI-miJWBy4ygGtLBpp9PxoAR7MAlazIX0gfA
          name: Authorization
          description: ''
          schema:
            type: string
          in: header
          required: true
      responses:
        '200':
          $ref: '#/components/responses/CartoesResponse'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cartao'
            examples:
              cartao:
                value:
                  numero: some text
                  nome: some text
                  vencimento: some text
                  cvv: 5
        required: true
      parameters:
        -
          examples:
            token jwt:
              value: >-
                Bearer
                eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjYXJsb3NAZ21haWwuY29tIiwiZXhwIjoxNjM2NTg3OTAyfQ.osNc62Q6x-awAxXjeSwKMBaLS2TPD0S0sGicAuNhAxnDJBtALaaoNbIfkD8i5WFUO7s3rtuEu0Yr66ZeKGnyTg
          name: Authorization
          description: ''
          schema:
            type: string
          in: header
          required: true
      responses:
        '200':
          $ref: '#/components/responses/CartaoResponse'
        '400':
          $ref: '#/components/responses/InfoErro'
        '401':
          $ref: '#/components/responses/InfoErro'
        '404':
          $ref: '#/components/responses/InfoErro'
        '500':
          $ref: '#/components/responses/InfoErro'
components:
  schemas:
    Produto:
      title: Root Type for Produto
      description: ''
      type: object
      properties:
        id:
          format: int32
          type: integer
        nome:
          type: string
        url:
          type: string
        preco:
          format: double
          type: number
        desconto:
          format: int32
          type: integer
      example:
        id: 1
        nome: casaco
        url: casaco.com
        preco: 99.99
        desconto: 20
    Error:
      title: Root Type for Error
      description: ''
      type: object
      properties:
        mensagem:
          type: string
      example:
        mensagem: error
    Categoria:
      title: Root Type for Categoria
      description: ''
      type: object
      properties:
        id:
          format: int32
          type: integer
        descricao:
          type: string
      example:
        id: 1
        descricao: TODOS
    ProdutoCategorizado:
      title: Root Type for ProdutoCategorizado
      description: ''
      type: object
      properties:
        id:
          format: int32
          type: integer
        nome:
          type: string
        url:
          type: string
        preco:
          format: double
          type: number
        desconto:
          format: int32
          type: integer
        categorias:
          type: array
          items:
            $ref: '#/components/schemas/Categoria'
          properties:
            id:
              format: int32
              type: integer
            descricao:
              type: string
      example:
        id: 23
        nome: some text
        url: some text
        preco: 75.52
        desconto: 53
        categoria:
          -
            id: 38
            descricao: some text
          -
            id: 66
            descricao: some text
    Cartao:
      title: Root Type for Cartao
      description: ''
      type: object
      properties:
        numero:
          type: string
        nome:
          type: string
        vencimento:
          type: string
        cvv:
          format: int32
          type: integer
      example:
        numero: '123456'
        nome: nome
        vencimento: 12/30
        cvv: 123
  responses:
    ProdutosEmPromocao:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Produto'
          examples:
            Produtos em promocao:
              value:
                -
                  id: 5
                  nome: some text
                  url: some text
                  preco: 14.14
                  desconto: 28
                -
                  id: 28
                  nome: some text
                  url: some text
                  preco: 76.43
                  desconto: 65
      description: Produtos em promoção
    InfoErro:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Erro:
              value:
                mensagem: some text
      description: ''
    CategoriasResponse:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Categoria'
          examples:
            Categorias:
              value:
                -
                  id: 38
                  descricao: some text
                -
                  id: 55
                  descricao: some text
      description: ''
    ProdutoReponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Produto'
          examples:
            Produto Criado:
              value:
                id: 85
                nome: some text
                url: some text
                preco: 88.8
                desconto: 43
      description: ''
    ProdutoCategorizado:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ProdutoCategorizado'
          examples:
            Produtos Categorizado:
              value:
                -
                  id: 25
                  nome: some text
                  url: some text
                  preco: 11.07
                  desconto: 18
                  categoria:
                    id: 1
                    descricao: some text
                -
                  id: 6
                  nome: some text
                  url: some text
                  preco: 38.34
                  desconto: 67
                  categoria:
                    id: 31
                    descricao: some text
      description: ''
    CartaoResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cartao'
          examples:
            cartaoResponse:
              value:
                numero: some text
                nome: some text
                vencimento: some text
                cvv: 3
      description: ''
    CartoesResponse:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Cartao'
          examples:
            cartao:
              value:
                -
                  numero: some text
                  nome: some text
                  vencimento: some text
                  cvv: 71
                -
                  numero: some text
                  nome: some text
                  vencimento: some text
                  cvv: 64
      description: ''
